import QRCode from "qrcode";

/** The terminal renderer paints black modules on a white background. */
const QR_OPEN = "\x1b[47m\x1b[30m";
const QR_CLOSE = "\x1b[0m";

/**
 * Renders the pairing QR.
 *
 * Generated by a real encoder at error-correction level M. Nothing is drawn
 * inside the module area and nothing is substituted for the code — scan
 * reliability is not negotiable for decoration (§10).
 *
 * The quiet zone is added here rather than passed as an option: node-qrcode's
 * terminal renderer ignores `margin` when `small` is set, and ships only a
 * single module of padding. The standard wants four, and without it the finder
 * patterns sit flush against surrounding terminal text, which measurably hurts
 * scanning. Each rendered row is two modules tall (half-blocks), so two blank
 * rows above and below give the four modules vertically, and three extra
 * columns each side top up the one already present.
 */
export async function renderQr(url: string): Promise<string[]> {
  const art = await QRCode.toString(url, {
    type: "terminal",
    small: true,
    errorCorrectionLevel: "M",
  });

  const rows = art
    .split("\n")
    .filter((line) => stripAnsi(line).length > 0)
    // Drop only the wrapper this renderer adds. Interior codes are left alone:
    // the final half-row recolours per cell, and rewriting that would corrupt
    // the modules themselves.
    .map((line) => line.replace(new RegExp(`^${escapeRe(QR_OPEN)}`), "").replace(/\x1b\[0m$/, ""));

  if (rows.length === 0) return [];

  const SIDE = 3;
  // Width must be measured in visible cells: the last row carries per-cell
  // escape sequences, and counting those would blow the quiet zone out to
  // hundreds of columns.
  const content = Math.max(...rows.map((row) => visibleLength(row)));
  const width = content + SIDE * 2;
  const blank = `${QR_OPEN}${" ".repeat(width)}${QR_CLOSE}`;

  const padded = rows.map((row) => {
    const trailing = " ".repeat(Math.max(0, content - visibleLength(row)));
    return `${QR_OPEN}${" ".repeat(SIDE)}${row}${trailing}${" ".repeat(SIDE)}${QR_CLOSE}`;
  });

  return [blank, blank, ...padded, blank, blank];
}

// eslint-disable-next-line no-control-regex
const ANSI = /\x1b\[[0-9;]*m/g;

function stripAnsi(text: string): string {
  return text.replace(ANSI, "");
}

/** Visible cell count, ignoring escape sequences. */
export function visibleLength(text: string): number {
  return stripAnsi(text).length;
}

function escapeRe(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
