/** Renders every expression and writes src/components/brand/sprite-data.ts. */
import { writeFileSync } from "node:fs";
import { draw, EXPRESSIONS, SIZE } from "./gen-sloth.mjs";

const SHADE = { ".": " ", o: "#", H: "@", h: "%", L: "+", F: "o", M: ".", P: "X", e: "=", n: "*", w: "O" };

const variants = {};
for (const e of EXPRESSIONS) {
  const rows = draw(e);
  if (rows.length !== SIZE || rows.some((r) => r.length !== SIZE)) {
    throw new Error(`sprite "${e}" is not ${SIZE}x${SIZE}`);
  }
  variants[e] = rows;
}

if (process.argv.includes("--preview")) {
  const which = process.argv[process.argv.indexOf("--preview") + 1] ?? "idle";
  console.log(variants[which].map((r) => [...r].map((c) => SHADE[c]).join("")).join("\n"));
  process.exit(0);
}

const body = `// GENERATED by scripts/build-sprite.mjs — do not edit by hand.
// Run \`pnpm sprite\` after changing scripts/gen-sloth.mjs.

/**
 * BIT — the Lazy Skill mascot. A sleepy sloth in a hoodie.
 *
 * Stored as a ${SIZE}x${SIZE} character grid rather than SVG paths so one source
 * scales crisply to any size, retints with the active theme, and swaps
 * expression without a second asset.
 *
 * Legend: . transparent | o outline | H hood | h hood shadow | L hood light
 *         F fur | M muzzle | P eye patch | e eye | n nose | w eye white
 */

export const SPRITE_SIZE = ${SIZE};

/** Palette keys resolve against CSS custom properties, so themes apply free. */
export const PX: Record<string, string | null> = {
  ".": null,
  o: "#120d1c",
  H: "var(--ls-accent)",
  h: "var(--ls-accent-lo)",
  L: "var(--ls-accent-hi)",
  F: "#e3c9a4",
  M: "#f6e6cd",
  P: "#5b4130",
  e: "#2c1e16",
  n: "#3d2b20",
  w: "#fdf6ea",
};

export const EXPRESSIONS = ${JSON.stringify(EXPRESSIONS)} as const;

export type Expression = (typeof EXPRESSIONS)[number];

export const SPRITES: Record<Expression, string[]> = {
${EXPRESSIONS.map((e) => `  ${e}: [\n${variants[e].map((r) => `    "${r}",`).join("\n")}\n  ],`).join("\n")}
};

export function spriteRows(expression: Expression): string[] {
  return SPRITES[expression] ?? SPRITES.idle;
}
`;

writeFileSync(new URL("../src/components/brand/sprite-data.ts", import.meta.url), body);

// The CLI ships as its own package and cannot import from the app, so it gets
// a generated copy from the same source. Both are regenerated together, so
// the mascot can never differ between the terminal and the phone.
const cliBody = body.replace(
  'export const PX: Record<string, string | null> = {',
  `/** Terminal colours are literal RGB — no CSS variables to resolve. The hood
 * is substituted per theme at render time; everything else is fixed. */
export const PX: Record<string, string | null> = {`
);
writeFileSync(new URL("../cli/src/ui/sprite-data.ts", import.meta.url), cliBody);

console.log(`wrote sprite-data.ts (app + cli) — ${EXPRESSIONS.length} expressions @ ${SIZE}x${SIZE}`);
