import type { Skill } from "@/types/skill";

/**
 * SAMPLE CONTENT — not a registry mirror.
 *
 * Every record is namespaced under the `demo` owner and carries isDemo: true
 * so it can never be mistaken for a real published skill (§62). Install
 * counts here are illustrative fixtures for layout work; the live provider
 * will replace them wholesale with reported values.
 */

type Seed = Omit<Skill, "id" | "slug" | "source" | "sourceType" | "isDemo" | "repoUrl"> & {
  key: string;
};

const seeds: Seed[] = [
  {
    key: "browser-automation",
    name: "Browser Automation",
    summary: "Drive a real browser: click, type, scrape, screenshot.",
    description:
      "Gives your agent a headless browser it can actually steer. Navigate pages, fill forms, wait on selectors, extract structured data, and capture screenshots — without you writing a single line of Playwright.",
    installs: 24_200,
    trendingRank: 1,
    compatibility: ["claude", "codex", "cursor"],
    categories: ["automation", "development"],
    license: "MIT",
    updatedAt: "2026-08-24",
    audits: [{ provider: "Sample Audit", status: "pass", riskLevel: "low" }],
    installRef: "demo/browser-automation",
    homepageUrl: null,
  },
  {
    key: "deep-research",
    name: "Deep Research",
    summary: "Multi-source research with citations that actually resolve.",
    description:
      "Plans a research path, reads across sources, cross-checks claims, and hands back a brief where every assertion links to something you can open.",
    installs: 18_940,
    trendingRank: 2,
    compatibility: ["claude", "codex"],
    categories: ["research", "productivity"],
    license: "Apache-2.0",
    updatedAt: "2026-08-29",
    audits: [{ provider: "Sample Audit", status: "pass", riskLevel: "low" }],
    installRef: "demo/deep-research",
    homepageUrl: null,
  },
  {
    key: "code-reviewer",
    name: "Code Reviewer",
    summary: "Diff-aware review that flags bugs, not formatting.",
    description:
      "Reads the diff in the context of the surrounding code, then reports correctness risks with a concrete failure scenario for each. Skips the nitpicks your linter already caught.",
    installs: 31_700,
    trendingRank: 3,
    compatibility: ["claude", "codex", "cursor", "copilot"],
    categories: ["development", "security"],
    license: "MIT",
    updatedAt: "2026-08-30",
    audits: [{ provider: "Sample Audit", status: "pass", riskLevel: "low" }],
    installRef: "demo/code-reviewer",
    homepageUrl: null,
  },
  {
    key: "react-refactor",
    name: "React Refactor",
    summary: "Untangle components, hooks, and the state that leaked.",
    description:
      "Finds oversized components, lifts state to where it belongs, extracts hooks, and keeps the render tree honest.",
    installs: 12_450,
    trendingRank: 7,
    compatibility: ["claude", "cursor"],
    categories: ["development"],
    license: "MIT",
    updatedAt: "2026-08-12",
    audits: null,
    installRef: "demo/react-refactor",
    homepageUrl: null,
  },
  {
    key: "seo-audit",
    name: "SEO Audit",
    summary: "Crawl a site, rank what is actually costing you traffic.",
    description:
      "Walks the sitemap, checks metadata, headings, canonical tags, and Core Web Vitals, then orders the findings by likely traffic impact instead of alphabetically.",
    installs: 9_320,
    trendingRank: null,
    compatibility: ["claude"],
    categories: ["marketing", "research"],
    license: "MIT",
    updatedAt: "2026-07-30",
    audits: [{ provider: "Sample Audit", status: "pass", riskLevel: "low" }],
    installRef: "demo/seo-audit",
    homepageUrl: null,
  },
  {
    key: "youtube-summarizer",
    name: "YouTube Summarizer",
    summary: "Turn a 90-minute video into the 6 lines that mattered.",
    description:
      "Pulls the transcript, segments it by topic, and returns timestamped takeaways you can jump straight to.",
    installs: 27_800,
    trendingRank: 4,
    compatibility: ["claude", "codex"],
    categories: ["productivity", "research"],
    license: "MIT",
    updatedAt: "2026-08-27",
    audits: null,
    installRef: "demo/youtube-summarizer",
    homepageUrl: null,
  },
  {
    key: "pixel-art-gen",
    name: "Pixel Art Generator",
    summary: "Sprites, tilesets, and palettes on a strict grid.",
    description:
      "Generates pixel art that respects a fixed palette and grid size, so the output drops straight into a game engine instead of needing a cleanup pass.",
    installs: 6_110,
    trendingRank: null,
    compatibility: ["claude"],
    categories: ["design"],
    license: "CC-BY-4.0",
    updatedAt: "2026-06-18",
    audits: null,
    installRef: "demo/pixel-art-gen",
    homepageUrl: null,
  },
  {
    key: "terraform-planner",
    name: "Terraform Planner",
    summary: "Explain the plan before it wrecks the cluster.",
    description:
      "Reads `terraform plan` output and translates it into what will actually change, what is destructive, and what is safe to apply unattended.",
    installs: 8_760,
    trendingRank: null,
    compatibility: ["claude", "codex"],
    categories: ["devops"],
    license: "MPL-2.0",
    updatedAt: "2026-08-05",
    audits: [{ provider: "Sample Audit", status: "warn", riskLevel: "medium" }],
    installRef: "demo/terraform-planner",
    homepageUrl: null,
  },
  {
    key: "sql-explain",
    name: "SQL Explainer",
    summary: "Read the query plan so you do not have to.",
    description:
      "Takes an EXPLAIN ANALYZE dump and tells you which scan is the problem and which index would fix it.",
    installs: 14_020,
    trendingRank: 9,
    compatibility: ["claude", "codex", "cursor"],
    categories: ["data", "development"],
    license: "MIT",
    updatedAt: "2026-08-19",
    audits: null,
    installRef: "demo/sql-explain",
    homepageUrl: null,
  },
  {
    key: "threat-model",
    name: "Threat Modeller",
    summary: "STRIDE on your actual architecture, not a template.",
    description:
      "Reads your service topology and produces a threat model grounded in the trust boundaries that really exist in the code.",
    installs: 4_480,
    trendingRank: null,
    compatibility: ["claude"],
    categories: ["security"],
    license: "Apache-2.0",
    updatedAt: "2026-07-11",
    audits: [{ provider: "Sample Audit", status: "pass", riskLevel: "low" }],
    installRef: "demo/threat-model",
    homepageUrl: null,
  },
  {
    key: "changelog-writer",
    name: "Changelog Writer",
    summary: "Commits in. Release notes humans will read out.",
    description:
      "Groups commits by user-visible impact, drops the chores, and writes notes in your project's existing voice.",
    installs: 11_240,
    trendingRank: null,
    compatibility: ["claude", "codex", "cursor"],
    categories: ["development", "productivity"],
    license: "MIT",
    updatedAt: "2026-08-21",
    audits: null,
    installRef: "demo/changelog-writer",
    homepageUrl: null,
  },
  {
    key: "design-tokens",
    name: "Design Token Sync",
    summary: "One palette. Figma, CSS, and native stay in step.",
    description:
      "Keeps a single token source in sync across design and code, and reports drift when someone hardcodes a hex.",
    installs: 5_930,
    trendingRank: null,
    compatibility: ["claude", "cursor"],
    categories: ["design", "development"],
    license: "MIT",
    updatedAt: "2026-07-28",
    audits: null,
    installRef: "demo/design-tokens",
    homepageUrl: null,
  },
  {
    key: "inbox-triage",
    name: "Inbox Triage",
    summary: "Sort, draft, and never open the promotions tab.",
    description:
      "Classifies incoming mail by what it needs from you, drafts the two-line replies, and leaves everything else alone.",
    installs: 16_390,
    trendingRank: 8,
    compatibility: ["claude"],
    categories: ["productivity", "automation"],
    license: "MIT",
    updatedAt: "2026-08-26",
    audits: null,
    installRef: "demo/inbox-triage",
    homepageUrl: null,
  },
  {
    key: "agent-orchestrator",
    name: "Agent Orchestrator",
    summary: "Fan work out to sub-agents, merge the results.",
    description:
      "Splits a task across parallel agents, tracks what each returned, and reconciles conflicting answers instead of taking the last one.",
    installs: 21_070,
    trendingRank: 5,
    compatibility: ["claude", "codex"],
    categories: ["ai-agents", "automation"],
    license: "Apache-2.0",
    updatedAt: "2026-08-28",
    audits: [{ provider: "Sample Audit", status: "pass", riskLevel: "low" }],
    installRef: "demo/agent-orchestrator",
    homepageUrl: null,
  },
  {
    key: "memory-keeper",
    name: "Memory Keeper",
    summary: "Long-term recall your agent does not hallucinate.",
    description:
      "Stores durable facts with provenance and expiry, and refuses to surface anything it cannot attribute.",
    installs: 13_580,
    trendingRank: 10,
    compatibility: ["claude", "codex", "cursor"],
    categories: ["ai-agents"],
    license: "MIT",
    updatedAt: "2026-08-23",
    audits: null,
    installRef: "demo/memory-keeper",
    homepageUrl: null,
  },
  {
    key: "csv-wrangler",
    name: "CSV Wrangler",
    summary: "Messy spreadsheet in, clean dataframe out.",
    description:
      "Infers types, repairs delimiters, normalises dates, and tells you exactly which rows it could not parse.",
    installs: 7_640,
    trendingRank: null,
    compatibility: ["claude", "codex"],
    categories: ["data"],
    license: "BSD-3-Clause",
    updatedAt: "2026-07-02",
    audits: null,
    installRef: "demo/csv-wrangler",
    homepageUrl: null,
  },
  {
    key: "k8s-doctor",
    name: "Kubernetes Doctor",
    summary: "CrashLoopBackOff, explained in one paragraph.",
    description:
      "Correlates pod events, logs, and resource limits to name the actual cause instead of listing the symptoms.",
    installs: 10_910,
    trendingRank: null,
    compatibility: ["claude", "codex"],
    categories: ["devops"],
    license: "Apache-2.0",
    updatedAt: "2026-08-16",
    audits: [{ provider: "Sample Audit", status: "pass", riskLevel: "low" }],
    installRef: "demo/k8s-doctor",
    homepageUrl: null,
  },
  {
    key: "landing-copy",
    name: "Landing Page Copy",
    summary: "Headlines that say what the product does.",
    description:
      "Writes hero, feature, and CTA copy from your positioning, and refuses to ship a headline containing the word 'seamless'.",
    installs: 8_150,
    trendingRank: null,
    compatibility: ["claude"],
    categories: ["marketing"],
    license: "MIT",
    updatedAt: "2026-08-09",
    audits: null,
    installRef: "demo/landing-copy",
    homepageUrl: null,
  },
  {
    key: "test-generator",
    name: "Test Generator",
    summary: "Tests for the branches you forgot existed.",
    description:
      "Reads a module, maps its branches, and writes the cases that are actually uncovered — with real assertions, not snapshots.",
    installs: 19_460,
    trendingRank: 6,
    compatibility: ["claude", "codex", "cursor", "copilot"],
    categories: ["development"],
    license: "MIT",
    updatedAt: "2026-08-25",
    audits: null,
    installRef: "demo/test-generator",
    homepageUrl: null,
  },
  {
    key: "api-mocker",
    name: "API Mocker",
    summary: "Spin a fake backend from an OpenAPI spec.",
    description:
      "Reads a spec and serves a mock that honours its schemas, so the frontend stops waiting on the backend.",
    installs: 6_720,
    trendingRank: null,
    compatibility: ["claude", "cursor"],
    categories: ["development", "automation"],
    license: "MIT",
    updatedAt: "2026-06-29",
    audits: null,
    installRef: "demo/api-mocker",
    homepageUrl: null,
  },
  {
    key: "competitor-watch",
    name: "Competitor Watch",
    summary: "Track their pricing page so you do not have to.",
    description:
      "Snapshots competitor pages on a schedule and reports only the diffs that matter — pricing, positioning, new features.",
    installs: 5_280,
    trendingRank: null,
    compatibility: ["claude"],
    categories: ["marketing", "research"],
    license: "MIT",
    updatedAt: "2026-07-19",
    audits: null,
    installRef: "demo/competitor-watch",
    homepageUrl: null,
  },
  {
    key: "dep-auditor",
    name: "Dependency Auditor",
    summary: "Which CVE actually reaches your code path.",
    description:
      "Cross-references advisories against real import paths, so you patch the three that matter instead of all forty.",
    installs: 9_880,
    trendingRank: null,
    compatibility: ["claude", "codex"],
    categories: ["security", "devops"],
    license: "Apache-2.0",
    updatedAt: "2026-08-14",
    audits: [{ provider: "Sample Audit", status: "pass", riskLevel: "low" }],
    installRef: "demo/dep-auditor",
    homepageUrl: null,
  },
  {
    key: "meeting-notes",
    name: "Meeting Notes",
    summary: "Transcript in, decisions and owners out.",
    description:
      "Extracts decisions, action items, and owners — and flags the questions the meeting left unanswered.",
    installs: 15_730,
    trendingRank: null,
    compatibility: ["claude", "codex"],
    categories: ["productivity"],
    license: "MIT",
    updatedAt: "2026-08-22",
    audits: null,
    installRef: "demo/meeting-notes",
    homepageUrl: null,
  },
  {
    key: "chart-builder",
    name: "Chart Builder",
    summary: "Data to a chart that reads correctly in both themes.",
    description:
      "Picks the right mark for the question, applies an accessible palette, and never renders a 3D pie chart.",
    installs: 7_050,
    trendingRank: null,
    compatibility: ["claude", "cursor"],
    categories: ["data", "design"],
    license: "MIT",
    updatedAt: "2026-08-01",
    audits: null,
    installRef: "demo/chart-builder",
    homepageUrl: null,
  },
  {
    key: "scraper-kit",
    name: "Scraper Kit",
    summary: "Polite crawling with rate limits built in.",
    description:
      "Respects robots.txt and backs off on 429s by default, because the fastest scraper is the one that does not get blocked.",
    installs: 12_990,
    trendingRank: null,
    compatibility: ["claude", "codex"],
    categories: ["automation", "data"],
    license: "MIT",
    updatedAt: "2026-08-11",
    audits: [{ provider: "Sample Audit", status: "warn", riskLevel: "medium" }],
    installRef: "demo/scraper-kit",
    homepageUrl: null,
  },
  {
    key: "voice-notes",
    name: "Voice Notes",
    summary: "Talk at your laptop. Get structured notes.",
    description:
      "Transcribes, punctuates, and files a rambling voice memo into the right project without you touching it.",
    installs: 4_910,
    trendingRank: null,
    compatibility: null, // deliberately unknown — exercises the §19 fallback
    categories: ["productivity"],
    license: null,
    updatedAt: "2026-05-27",
    audits: null,
    installRef: "demo/voice-notes",
    homepageUrl: null,
  },
];

export const DEMO_SKILLS: Skill[] = seeds.map((seed) => {
  const { key, ...rest } = seed;
  return {
    ...rest,
    id: `demo/${key}`,
    slug: `demo/${key}`,
    source: "demo",
    sourceType: "unknown" as const,
    repoUrl: null,
    isDemo: true,
  };
});
